### ISSUE TITLE
Status and proposal 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/research#148] opened 2024-06-23 22:00 UTC
@0x4007 @diamondnegroni 

### Intro
I have been part of Ubiquity for over 2 years. During this time, I have done a variety of projects, most of which were completed with a positive outcome.
All this time, I have tried to understand and implement Alex's vision and help Ubiquity succeed.

### Card payments
In June 2024, a large project was completed - the card payments.
Research lasted about 10 months and implementation was about 5 months.
The implementation task 
- https://github.com/ubiquity/card-issuance/issues/34
My help for implementation consists of providing accesses to developers, cards activation and testing, consultation on the cards, research of the issues, getting help from the Reloadly support, etc.

Alex was skeptical about this solution at first, but in reality, it turned out to be acceptable and was integrated.
The project was completed successfully:
- Ubiquity now has the ability to pay contributors from most countries in the world using cards, while maintaining anonymity of their expenses.
- The solution is practically free, which has ALREADY saved Ubiquity money.
The lowest setup fee of the "classic" card provider exceeds all of Ubiquity's costs ie my payment for and implementation cost.
In addition to the setup fee, "classic" card providers also charge monthly expenses, while this solution not, so the Ubiquity cost savings will increase. 
- This provider allows us to top up your account with crypto, which makes the payment flow independent of banks with their risks of stopping payments.

### Preparing for Series A
In April - May 2024, I conducted research to prepare for Series A fundraising. 
During the research, I interviewed a number of professional influencers and investors who, on the condition of independence and anonymity, shared their feedback and recommendations on how Ubiquity should organize the next round of financing.

The research report will include aggregated feedback on areas important to investors, as well as recommendations. The recommendations have a number of insights on how to unlock Ubiquity's potential and significantly improve its position to obtain favorable fundraising terms.
It will be much more productive to perform tasks on Series A after analyzing this report
https://github.com/ubiquity/series-a/issues

### Other tasks
In addition to the activities described above, in April-May-June 2024 I performed a number of others:
- Tracked and shared important updates from companies that Alex identified as interesting for cooperation.
Among them are Microsoft, GitHub, Gnosis, Taiko because of the grant, and others.
- Communicated with the marketing agency that supported ChainGPT.
- Prepared my version of the pitch deck format based on the visual style created by Alex.
It is in the same folder where the pitch deck versions prepared by Alex are
https://drive.google.com/drive/folders/1a_lj1nWuHg8M1Hrtaz6DXG4nolcV9w3Y 
- I searched for lead gen until I realized that Alex had already found it.
- I did a mini-research on new requests, for example,
Ubiquity Credit https://github.com/ubiquity/.github/issues/110
Autonomous Coding Agent https://github.com/ubiquity/.github/issues/105

## Issues
For some reason unknown to me, Alex stopped giving me tasks, paying me, and responding to messages in Telegram. Previously, there were situations when Alex did not respond to messages for a long time, but later we returned to more frequent interaction.

### Base payment
There is an agreement that I receive a base payment as one of the core contributors.
A lot of my activities are done outside of GitHub, it is difficult to accurately calculate it using bounties and comment incentives.
Alex stopped sending base payments in April 2024 and does not respond to my messages on Telegram.

Alex wrote in the general Telegram chat, but did not respond to my dm:
アレクサンダー.eth | U B I Q U I T Y, [5/7/2024 11:09 AM]
attention to all core contributors who receive a base pay:
there were some issues with the current payroll system which led to lost funds (sent to wrong people/ex contributors etc) so i spent some time to redo it. 
in order for it to have the most accurate and up-to-date data, please dm me your wallet address you wish to receive xdai at. i will manually calculate the backpay for each contributor. 
thanks!

### Bounties
I have not received payment for already completed bounties.
- https://github.com/ubiquity/card-issuance/issues/26 completed by me, task is closed, unclear how to get payment. 
- https://github.com/ubiquity/card-issuance/issues/39 is actually completed by me, I even spent my own money to test this task, task is not closed, unclear how to get payment. 
- https://github.com/ubiquity/card-issuance/issues/34 my support for this task was completed, task is closed, unclear how to get payment. 

## Proposal
- I will complete the research report for series A fundraising and make a pull request at the beginning of July 2024.
- Alex will pay the missing base payment for April and May 2024, as well as for the completed bounties.
In June 2024, I completed much less tasks due to being sick, so the base pay for June can be reduced.
- From July 2024, I ask Alex to set me tasks to prepare for the fundraising, improve the content on the site, and other tasks for the development of Ubiquity.

If you have other suggestions, please let me know.

**Comment by 0x4007** [comment] 2024-06-26 19:49
Thank you for your detailed writeup on the work you have done for Ubiquity. I appreciate your efforts and the initiative you’ve shown. I apologize for the lack of communication and for any inconvenience caused by the delay in payments. I understand how frustrating this situation must have been for you.

### Card Payments Project
I acknowledge the completion and success of the card payments project. The implementation is of significant strategic importance to Ubiquity, and your contributions are appreciated.

### Base Pay and Rewards
1. **Base Pay**: Given the lack of deliverables over the past months and our organization’s emphasis on performance pay, I concluded that you were no longer actively contributing. This has happened with other contributors in the past, so I was not surprised to see this again.

As a gesture for your tenure and my lack of proper expectation management, I can provide a month of severance pay in addition to the rewards. You are invited to continue contributing to Ubiquity on a performance pay basis, utilizing the Conversation Rewards system and other deliverable-based payments. Please ensure to document your research and contributions via GitHub comments under the relevant issues to align with our auditing system. Unfortunately, any work that doesn't have deliverables or any metrics can't be managed, and as such can't be rewarded. I hope you understand where I am coming from.

2. **Task Rewards**: I will make the repository public and generate the permits soon, ensuring you receive the due payments. Please be sure to post any miscellaneous costs incurred with card top-ups, etc., and those can be manually sent. I appreciate your patience and the personal resources you invested in completing these tasks.

If there are specific questions you have, we should discuss them in direct messages. As you know, I generally strive to minimize direct messages for scaling purposes, but I understand that you may have some other concerns to go over. I am committed to ensuring that your contributions are recognized and compensated appropriately within our performance-based framework.

Thank you once again for your understanding and contributions to Ubiquity.

https://gnosisscan.io/tx/0x8bd641e5838e23c5e1fd348b27053cacd0cc0e92dec695e85ba274acd470b07b

**Closed as completed** 2024-06-26 19:59 UTC

**Comment by sergfeldman** [comment] 2024-06-27 10:59
@0x4007 Thank you for the detailed answer.

As you haven't read my Telegram messages since the beginning of May, I have to ask here.
Part of my compensation was 2500 UBQ per month.
The last time I received UBQ was for February 2024.
Can you please send UBQ for the months I was a core contributor?

**Comment by 0x4007** [comment] 2024-06-27 19:06
https://etherscan.io/tx/0x0be624572ac97479fe036dd30a9a660fe8e61f63a45452d1e4445b90493cda90
